//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeerCopyWPF.Strings.en_US {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeerCopyWPF.Strings.en_US.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Use arrow keys to resize selection.
        /// </summary>
        public static string ArrowKeysLblStr {
            get {
                return ResourceManager.GetString("ArrowKeysLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Clear selection.
        /// </summary>
        public static string ClearLblStr {
            get {
                return ResourceManager.GetString("ClearLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Copy selection to clipboard.
        /// </summary>
        public static string CopyLblStr {
            get {
                return ResourceManager.GetString("CopyLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Edit selection with default editor.
        /// </summary>
        public static string EditLblStr {
            get {
                return ResourceManager.GetString("EditLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Take new Leer.
        /// </summary>
        public static string NewLeerLblStr {
            get {
                return ResourceManager.GetString("NewLeerLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Exit Leer Copy.
        /// </summary>
        public static string QuitLblStr {
            get {
                return ResourceManager.GetString("QuitLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Save selection to file.
        /// </summary>
        public static string SaveLblStr {
            get {
                return ResourceManager.GetString("SaveLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Open settings.
        /// </summary>
        public static string SettingsWinLblStr {
            get {
                return ResourceManager.GetString("SettingsWinLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Toggle tips on/off.
        /// </summary>
        public static string TipsLblStr {
            get {
                return ResourceManager.GetString("TipsLblStr", resourceCulture);
            }
        }
    }
}
