//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeerCopyWPF.Strings.en_US {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeerCopyWPF.Strings.en_US.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Use arrow keys to resize selection.
        /// </summary>
        public static string ArrowKeysLblStr {
            get {
                return ResourceManager.GetString("ArrowKeysLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Toggle border on/off.
        /// </summary>
        public static string BorderLblStr {
            get {
                return ResourceManager.GetString("BorderLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTURE OPTIONS.
        /// </summary>
        public static string CaptureOptionsStr {
            get {
                return ResourceManager.GetString("CaptureOptionsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Clear selection.
        /// </summary>
        public static string ClearLblStr {
            get {
                return ResourceManager.GetString("ClearLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Copy selection to clipboard.
        /// </summary>
        public static string CopyLblStr {
            get {
                return ResourceManager.GetString("CopyLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Edit selection with default editor.
        /// </summary>
        public static string EditLblStr {
            get {
                return ResourceManager.GetString("EditLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAboutStr {
            get {
                return ResourceManager.GetString("MenuAboutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExitStr {
            get {
                return ResourceManager.GetString("MenuExitStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFileStr {
            get {
                return ResourceManager.GetString("MenuFileStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettingsStr {
            get {
                return ResourceManager.GetString("MenuSettingsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Quit Selection.
        /// </summary>
        public static string QuitLblStr {
            get {
                return ResourceManager.GetString("QuitLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Save selection to file.
        /// </summary>
        public static string SaveLblStr {
            get {
                return ResourceManager.GetString("SaveLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Select entire screen.
        /// </summary>
        public static string SelectAllLblStr {
            get {
                return ResourceManager.GetString("SelectAllLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Capture.
        /// </summary>
        public static string SelectCaptureBtnStr {
            get {
                return ResourceManager.GetString("SelectCaptureBtnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Border Color:.
        /// </summary>
        public static string SettingsBorderColorStr {
            get {
                return ResourceManager.GetString("SettingsBorderColorStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Border Visible:.
        /// </summary>
        public static string SettingsBorderVisStr {
            get {
                return ResourceManager.GetString("SettingsBorderVisStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string SettingsColorStr {
            get {
                return ResourceManager.GetString("SettingsColorStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default File Ext:.
        /// </summary>
        public static string SettingsFileExtStr {
            get {
                return ResourceManager.GetString("SettingsFileExtStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default File Name:.
        /// </summary>
        public static string SettingsFileNameStr {
            get {
                return ResourceManager.GetString("SettingsFileNameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Bindings.
        /// </summary>
        public static string SettingsKeyBindingsStr {
            get {
                return ResourceManager.GetString("SettingsKeyBindingsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string SettingsMiscStr {
            get {
                return ResourceManager.GetString("SettingsMiscStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips Visible:.
        /// </summary>
        public static string SettingsTipsVisStr {
            get {
                return ResourceManager.GetString("SettingsTipsVisStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Open settings.
        /// </summary>
        public static string SettingsWinLblStr {
            get {
                return ResourceManager.GetString("SettingsWinLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Window Opacity:.
        /// </summary>
        public static string SettingsWinOpacityStr {
            get {
                return ResourceManager.GetString("SettingsWinOpacityStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Switch screens.
        /// </summary>
        public static string SwitchLblStr {
            get {
                return ResourceManager.GetString("SwitchLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Toggle tips on/off.
        /// </summary>
        public static string TipsLblStr {
            get {
                return ResourceManager.GetString("TipsLblStr", resourceCulture);
            }
        }
    }
}
